version: "3"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx
    container_name: autofica-gateway
    depends_on:
      - authentication-service
      - authentication-checker
      - strapi-service
    volumes:
      - ./services/autofica-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  # Dockerized mongodb instance
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27016:27017
  # Dockerized redis instance
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data

  # Authenticates users
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/admin
    build:
      context: ./packages/authentication-service
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    restart: on-failure
  # Authenticates requests
  authentication-checker:
    image: authentication-checker
    container_name: authentication-checker
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: ./packages/service-auth-request
    depends_on:
      - redis
    ports:
      - 3000:3000
    restart: on-failure
  # Main api
  strapi-service:
    image: strapi-service
    container_name: strapi-service
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
    build:
      context: ./packages/strapi-backend
    ports:
      - 1337:1337
    depends_on:
      - mongodb
    restart: on-failure
volumes:
  mongodata:
  redisdata:
